apiVersion: netscaler.com/v1
kind: NetscalerObservabilityExporter
metadata:
  name: nsoe
spec:
  # Default values copied from <project_dir>/helm-charts/netscaler-observability-exporter/values.yaml
  affinity: {}
  elasticsearch:
    enabled: false
    indexprefix: ""
    server: ""
  fullnameOverride: ""
  headless: false
  image: '{{ .Values.imageRegistry }}/{{ .Values.imageRepository }}:{{ .Values.imageTag
    }}'
  imageRegistry: quay.io
  imageRepository: netscaler/netscaler-observability-exporter
  imageTag: 1.9.001
  json_trans_rate_limiting:
    enabled: false
    limit: 100
    queuelimit: 1000
    window: 5
  kafka:
    auditlogs: "no"
    broker: ""
    dataFormat: AVRO
    enabled: false
    events: "no"
    topic: HTTP
  license:
    accept: "no"
  nameOverride: ""
  nodePortRequired: false
  ns_tracing:
    enabled: false
    server: zipkin:9411/api/v1/spans
  nsoeLogLevel: INFO
  podAnnotations: {}
  pullPolicy: IfNotPresent
  replicas: 1
  resources: {}
  splunk:
    authtoken: ""
    enabled: false
    indexprefix: ""
    server: ""
  timeseries:
    enabled: false
    nodePort: 30002
  tolerations: []
  transaction:
    nodePort: 30001
  
  
